### PR TITLE
Add 9 effects, modify 2 effects

### PR DESCRIPTION
**Pull request by Snazzah**
### New Effects:
- Disintegration Field (`disintegrationField`)
- SUPERTEARDOWN (`superhot`)
- Trigger Alarm (`triggerAlarm`)
- Teleport to Random Target (`teleportToTarget`)
- Teleport Random Target to Player (`teleportTarget`)
- Ghost Rider (`ghostRider`)
- Launch All Vehicles Up (`launchAllVehicles`)
- Virtual Reality (`vr`)
- Flashbang (`Flashbang`)
- Move or Die (`moveOrDie`)

### Modified Effects:
- One Hit KO (`oneHitKO`)
  - If the HP is not 1, then set to 0, rather than always be at 0.1 to avoid game effects
- I'm Tired (`tiredPlayer`)
  - If the HP is not 1, then set to 0, rather than always be at 0.1 to avoid game effects

[Here is my Steam profile](https://steamcommunity.com/id/Snazzah) for credit

### CODE REVIEW

**Comment by NLferdiNL** [comment]
I'm checking all the effects right now, your modifications seem fine on the existing effects. The One Hit KO is definitely better this way because low health is just a death sentence on challenges such as hunted.

For the tired effect I assume you mean the blur rather than health.

**Comment by NLferdiNL** [comment]
I've renamed Ghost Rider to Ghost Cars because I thought I was going to have a flaming head or something 😄 
(That is also a nod to the GTA SA days with the ghost cars myths and such.)

And I've made Superhot last twice as long because that is such a fun effect.

**Comment by NLferdiNL** [comment]
I've sent you a friend request on Steam to add you to the contributors there.

**Comment by Snazzah** [comment]
Confirmed the friend request. Yeah, I did mean to say I added blur to tiredPlayer.

**Pull request merged**
